name: Vanilla JS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm init -y
          npm install eslint clean-css-cli terser imagemin-cli --save-dev

      - name: Run ESLint (non-blocking)
        run: npx eslint . --ext .js || true

      - name: Run build
        run: node scripts/build.js || echo "⚠️ Build script not found, skipping."

      - name: Upload artifact
        if: ${{ hashFiles('dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.run_number }}-${{ github.sha }}-$(date +'%Y%m%d')
          path: dist

      - name: Create Git Tag
        if: github.ref == 'refs/heads/main'
        id: create_git_tag
        run: |
          VERSION="v$(date +'%Y.%m.%d-%H%M')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a $VERSION -m "Automated build $VERSION"
          git push origin $VERSION

      - name: Zip dist folder
        if: ${{ hashFiles('dist/**') != '' }}
        run: zip -r dist.zip dist

      - name: Create GitHub Release
        if: ${{ hashFiles('dist/**') != '' }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: ${{ hashFiles('dist/**') != '' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Notification
        if: github.ref == 'refs/heads/main'
        run: |
          echo "✅ Build & Release complete for $GITHUB_REPOSITORY@$GITHUB_SHA"
